### ISSUE TITLE
Markets Page 

### ISSUE THREAD

**Issue by surgiie** [surgiie/compean#10]
Im not sure if its just me but i find the markets page somewhat plain. I think we will go back to @Gostwow  original design and include the pictures in card style. I will work on getting pictures for that. Id also like to be able to dynamically update the time stamps for start and end after the market has past that current week and update to the following week. We can collaborate whats the best way to do this via slack.

**Comment by yarwest** [comment]
We can just make a folder with pictures and display a random one by
creating a random int.

Op donderdag 8 september 2016 heeft Sergio Compean <notifications@github.com>
het volgende geschreven:

**Comment by surgiie** [comment]
Yeah this can be 1 possible solution. I like it!

**Comment by yarwest** [comment]
@surgiie we could either generate a random number and save it in the table or get a random image in the view (which would mean that you get different images every time the view gets loaded)

**Comment by surgiie** [comment]
@yarwest Im open to anything for this page. I like the random image thing.

**Comment by yarwest** [comment]
@surgiie hey, I tried something, tell me what you think. I think it could be neat, but I think it needs some more market images to really work.

**Comment by surgiie** [comment]
Ill get some more images for this! Ill push them as soon as i get them! Thanks!

**Comment by yarwest** [comment]
Good stuff :) looking forward to it. No problem :D

**Comment by surgiie** [comment]
There are a few pictures in the markets folder in public/images/

Ill get some more for us though:)

**Comment by yarwest** [comment]
I guess we are done here? @surgiie or is there anything more to add to this page?

**Comment by surgiie** [comment]
I believe were done here.
