### ISSUE TITLE
Point system for users

### ISSUE THREAD

**Issue by surgiie** [surgiie/compean#6]
Need to map out how users will be able to receive points and spend points.

A way to allow promo codes to be used and get discounts.

**Comment by yarwest** [comment]
Perhaps people can receive points for referrals.
A new user can enter the username of the user that referred them or they use a unique link. After their first purchase the referring user gets their points.

**Comment by surgiie** [comment]
I like the idea of points via referrals. I wanted to be able to allow them to collect points per purchase too but wasnt sure what way to handle it. I wasnt sure how to award them points for cash transactions and we use square for credit cart payments. Perhaps Square has an API we can use to integrate our point system for credit card transaction?

**Comment by yarwest** [comment]
How about award points for placing an order online instead of for the actual transaction?

**Comment by surgiie** [comment]
@yarwest yeah I think is probably the best since we're not an actually doing any online transactions and will probably encourage customers to use the site more. How should we handle users spending the points? Or how can I handle this at the farmers markets?

**Comment by yarwest** [comment]
@surgiie I think it is best to handle all the point interaction on the website.
Maybe a way to handle it is give the user an option to use points for a discount when the order is being placed online. When they do that, simply reduce the price of their cart with 10% or something, and they can go to the farm and pay that price.

**Comment by surgiie** [comment]
@yarwest yes! this works for me and reduces having to do any interaction with the points at the farm or farmers market.  Since we are trying to avoid any actual transactions, this is a great solution honestly! If our business ever gets big then we can probably turn this point system to work with actual online transactions.

**Comment by yarwest** [comment]
@surgiie I'm glad :) if online transactions would be implemented you could do something like a checkout screen where the user can fill in a code or use points and pick their payment method before being redirected to either a payment screen or an 'order received' kind of screen

**Comment by surgiie** [comment]
Id honestly would love to handle online transactions if our business was big enough to meet requirements. The farmers markets that we do usually run from like 8am to 12pm and some customers cannot make it until closer to 12 for personal reasons or maybe they are just not morning people:p. Sometimes we may sell out of a particular produce and the customer who comes late will usually go buy from another competitor since we sold out, which is why i decided i wanted to create this pickup system for them and have a point system to encourage customers to use the site. They will request an order for pickup via the site, and then we can integrate this point system for this, then they will be able to pick up the order at the farmers market. Again if we ever make it big, we can probably add a delivery system on top of the pickup one. :) @yarwest Thanks for the ideas, i love them! keep em coming!:)

As far as the point system goes we can probably write our own or use a package via composer. Ive been looking at this one but again implementation doesn't seem terribly complicated and we can probably write our own. 

https://github.com/Trexology/laravel-pointable

**Comment by yarwest** [comment]
Will do :)
The point package looks suitable, but yeah I think it will be super easy to create a new one too.

**Comment by surgiie** [comment]
I honestly have so many ideas for this project(and other projects lol) but just dont have enough friends who know coding to help me out:/ lol So i really appreciate the help im getting from you guys!:)

**Comment by yarwest** [comment]
I think it is safe to say that this part is finished. The only thing we'd like to add is points for referrals, which is currently part of the backlog (issue #14 ).
