### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by surgiie** [surgiie/compean#7]
The home/landing page will be a display any announcements our company might have for the customers. When there are no records for our announcement model, we should have some kind of content take up the announcement's place. Perhaps some kind of static content? Some kind of call to action for the pickup/point system maybe?

**Comment by yarwest** [comment]
What kind of things would be posted in the announcements?

**Comment by surgiie** [comment]
@yarwest just things that we as a company would like to notify our customers. Examples:

We may decide not to show up to a market due to weather or emergencies, we'd like to notify our customers we wont be there. Or maybe were hosting a photo share contest on facebook then we'd like to post an announcement with contest details. etc.

**Comment by yarwest** [comment]
I think something along the lines of:
"There are no announcements right now
Subscribe to our mailing list or check us out on social media to stay up to date"
(just assuming there is social media, otherwise you can just drop that)
Not really sure what else could be added/

**Comment by yarwest** [comment]
Dammit, I messed it up.
But basically, pull request #9 takes care of this stuff

**Comment by surgiie** [comment]
okay sounds good. Im 
sorry ive been a bit busy today, but yeah that works for me. @yarwest :)
